"""
    Kalshi API.

    This documentation describes Kalshi's REST API  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import kalshi
from kalshi.model.ranged_market_position import RangedMarketPosition
globals()['RangedMarketPosition'] = RangedMarketPosition
from kalshi.model.user_get_ranged_market_position_response import UserGetRangedMarketPositionResponse


class TestUserGetRangedMarketPositionResponse(unittest.TestCase):
    """UserGetRangedMarketPositionResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUserGetRangedMarketPositionResponse(self):
        """Test UserGetRangedMarketPositionResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = UserGetRangedMarketPositionResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
