"""
    Kalshi API.

    This documentation describes Kalshi's REST API  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import kalshi
from kalshi.model.json_error import JSONError
from kalshi.model.order import Order
globals()['JSONError'] = JSONError
globals()['Order'] = Order
from kalshi.model.user_batch_orders_create_single_order_response import UserBatchOrdersCreateSingleOrderResponse


class TestUserBatchOrdersCreateSingleOrderResponse(unittest.TestCase):
    """UserBatchOrdersCreateSingleOrderResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUserBatchOrdersCreateSingleOrderResponse(self):
        """Test UserBatchOrdersCreateSingleOrderResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = UserBatchOrdersCreateSingleOrderResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
