"""
    Kalshi API.

    This documentation describes Kalshi's REST API  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import kalshi
from kalshi.api.users_api import UsersApi  # noqa: E501


class TestUsersApi(unittest.TestCase):
    """UsersApi unit test stubs"""

    def setUp(self):
        self.api = UsersApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_user_immediate_funding(self):
        """Test case for get_user_immediate_funding

        GetUserImmediateFunding  # noqa: E501
        """
        pass

    def test_get_user_withdrawal_available_balance(self):
        """Test case for get_user_withdrawal_available_balance

        GetUserWithdrawalAvailableBalance  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
