"""
    Kalshi API.

    This documentation describes Kalshi's REST API  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import kalshi
from kalshi.model.subscription_preference import SubscriptionPreference
globals()['SubscriptionPreference'] = SubscriptionPreference
from kalshi.model.change_subscription_response import ChangeSubscriptionResponse


class TestChangeSubscriptionResponse(unittest.TestCase):
    """ChangeSubscriptionResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testChangeSubscriptionResponse(self):
        """Test ChangeSubscriptionResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ChangeSubscriptionResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
