"""
    Kalshi API.

    This documentation describes Kalshi's REST API  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import kalshi
from kalshi.model.series import Series
globals()['Series'] = Series
from kalshi.model.get_series_by_ticker_response import GetSeriesByTickerResponse


class TestGetSeriesByTickerResponse(unittest.TestCase):
    """GetSeriesByTickerResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetSeriesByTickerResponse(self):
        """Test GetSeriesByTickerResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GetSeriesByTickerResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
