"""
    Kalshi API.

    This documentation describes Kalshi's REST API  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import kalshi
from kalshi.model.event_child_market import EventChildMarket
from kalshi.model.settlement_source import SettlementSource
globals()['EventChildMarket'] = EventChildMarket
globals()['SettlementSource'] = SettlementSource
from kalshi.model.event_data import EventData


class TestEventData(unittest.TestCase):
    """EventData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEventData(self):
        """Test EventData"""
        # FIXME: construct object with mandatory attributes with example values
        # model = EventData()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
