"""
    Kalshi API.

    This documentation describes Kalshi's REST API  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import kalshi
from kalshi.model.get_user_immediate_funding_response import GetUserImmediateFundingResponse


class TestGetUserImmediateFundingResponse(unittest.TestCase):
    """GetUserImmediateFundingResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetUserImmediateFundingResponse(self):
        """Test GetUserImmediateFundingResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GetUserImmediateFundingResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
