"""
    Kalshi API.

    This documentation describes Kalshi's REST API  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import kalshi
from kalshi.model.people_referred_list import PeopleReferredList
globals()['PeopleReferredList'] = PeopleReferredList
from kalshi.model.user_get_referral_info_response import UserGetReferralInfoResponse


class TestUserGetReferralInfoResponse(unittest.TestCase):
    """UserGetReferralInfoResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUserGetReferralInfoResponse(self):
        """Test UserGetReferralInfoResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = UserGetReferralInfoResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
