"""
    Kalshi API.

    This documentation describes Kalshi's REST API  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import kalshi
from kalshi.model.favorited_series import FavoritedSeries
globals()['FavoritedSeries'] = FavoritedSeries
from kalshi.model.user_get_favorited_series_response import UserGetFavoritedSeriesResponse


class TestUserGetFavoritedSeriesResponse(unittest.TestCase):
    """UserGetFavoritedSeriesResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUserGetFavoritedSeriesResponse(self):
        """Test UserGetFavoritedSeriesResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = UserGetFavoritedSeriesResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
