"""
    Kalshi API.

    This documentation describes Kalshi's REST API  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import kalshi
from kalshi.model.people_referred import PeopleReferred
globals()['PeopleReferred'] = PeopleReferred
from kalshi.model.people_referred_list import PeopleReferredList


class TestPeopleReferredList(unittest.TestCase):
    """PeopleReferredList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPeopleReferredList(self):
        """Test PeopleReferredList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PeopleReferredList()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
