"""
    Kalshi API.

    This documentation describes Kalshi's REST API  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import kalshi
from kalshi.model.deprecated_portfolio_measurement import DeprecatedPortfolioMeasurement
globals()['DeprecatedPortfolioMeasurement'] = DeprecatedPortfolioMeasurement
from kalshi.model.deprecated_user_get_portfolio_history_response import DeprecatedUserGetPortfolioHistoryResponse


class TestDeprecatedUserGetPortfolioHistoryResponse(unittest.TestCase):
    """DeprecatedUserGetPortfolioHistoryResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDeprecatedUserGetPortfolioHistoryResponse(self):
        """Test DeprecatedUserGetPortfolioHistoryResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = DeprecatedUserGetPortfolioHistoryResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
