"""
    Kalshi API.

    This documentation describes Kalshi's REST API  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import kalshi
from kalshi.api.events_api import EventsApi  # noqa: E501


class TestEventsApi(unittest.TestCase):
    """EventsApi unit test stubs"""

    def setUp(self):
        self.api = EventsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_event_by_ticker_cached(self):
        """Test case for get_event_by_ticker_cached

        GetEventByTickerCached  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
