"""
    Kalshi API.

    This documentation describes Kalshi's REST API  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import kalshi
from kalshi.model.portfolio_measurement import PortfolioMeasurement
globals()['PortfolioMeasurement'] = PortfolioMeasurement
from kalshi.model.user_get_current_portfolio_value_response import UserGetCurrentPortfolioValueResponse


class TestUserGetCurrentPortfolioValueResponse(unittest.TestCase):
    """UserGetCurrentPortfolioValueResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUserGetCurrentPortfolioValueResponse(self):
        """Test UserGetCurrentPortfolioValueResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = UserGetCurrentPortfolioValueResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
