"""
    Kalshi API.

    This documentation describes Kalshi's REST API  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import kalshi
from kalshi.model.series import Series
globals()['Series'] = Series
from kalshi.model.get_series_list_response import GetSeriesListResponse


class TestGetSeriesListResponse(unittest.TestCase):
    """GetSeriesListResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetSeriesListResponse(self):
        """Test GetSeriesListResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GetSeriesListResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
