"""
    Kalshi API.

    This documentation describes Kalshi's REST API  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import kalshi
from kalshi.model.market_history_candle_stick_info import MarketHistoryCandleStickInfo
globals()['MarketHistoryCandleStickInfo'] = MarketHistoryCandleStickInfo
from kalshi.model.get_candlestick_market_history_response import GetCandlestickMarketHistoryResponse


class TestGetCandlestickMarketHistoryResponse(unittest.TestCase):
    """GetCandlestickMarketHistoryResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetCandlestickMarketHistoryResponse(self):
        """Test GetCandlestickMarketHistoryResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GetCandlestickMarketHistoryResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
