"""
    Kalshi API.

    This documentation describes Kalshi's REST API  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import kalshi
from kalshi.model.event_child_market import EventChildMarket


class TestEventChildMarket(unittest.TestCase):
    """EventChildMarket unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEventChildMarket(self):
        """Test EventChildMarket"""
        # FIXME: construct object with mandatory attributes with example values
        # model = EventChildMarket()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
