"""
    Kalshi API.

    This documentation describes Kalshi's REST API  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import kalshi
from kalshi.model.user_batch_orders_create_single_order_response import UserBatchOrdersCreateSingleOrderResponse
globals()['UserBatchOrdersCreateSingleOrderResponse'] = UserBatchOrdersCreateSingleOrderResponse
from kalshi.model.user_batch_orders_create_response import UserBatchOrdersCreateResponse


class TestUserBatchOrdersCreateResponse(unittest.TestCase):
    """UserBatchOrdersCreateResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUserBatchOrdersCreateResponse(self):
        """Test UserBatchOrdersCreateResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = UserBatchOrdersCreateResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
