"""
    Kalshi API.

    This documentation describes Kalshi's REST API  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import kalshi
from kalshi.model.event_data import EventData
globals()['EventData'] = EventData
from kalshi.model.get_events_response import GetEventsResponse


class TestGetEventsResponse(unittest.TestCase):
    """GetEventsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetEventsResponse(self):
        """Test GetEventsResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GetEventsResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
