"""
    Kalshi API.

    This documentation describes Kalshi's REST API  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import kalshi
from kalshi.model.market_activity import MarketActivity
globals()['MarketActivity'] = MarketActivity
from kalshi.model.get_active_markets_response import GetActiveMarketsResponse


class TestGetActiveMarketsResponse(unittest.TestCase):
    """GetActiveMarketsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetActiveMarketsResponse(self):
        """Test GetActiveMarketsResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GetActiveMarketsResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
