"""
    Kalshi API.

    This documentation describes Kalshi's REST API  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import kalshi
from kalshi.model.market_transaction import MarketTransaction


class TestMarketTransaction(unittest.TestCase):
    """MarketTransaction unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMarketTransaction(self):
        """Test MarketTransaction"""
        # FIXME: construct object with mandatory attributes with example values
        # model = MarketTransaction()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
