"""
    Kalshi API.

    This documentation describes Kalshi's REST API  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import kalshi
from kalshi.model.deprecated_user_get_portfolio_history_request import DeprecatedUserGetPortfolioHistoryRequest


class TestDeprecatedUserGetPortfolioHistoryRequest(unittest.TestCase):
    """DeprecatedUserGetPortfolioHistoryRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDeprecatedUserGetPortfolioHistoryRequest(self):
        """Test DeprecatedUserGetPortfolioHistoryRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = DeprecatedUserGetPortfolioHistoryRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
