"""
    Kalshi API.

    This documentation describes Kalshi's REST API  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import kalshi
from kalshi.model.market_position import MarketPosition
globals()['MarketPosition'] = MarketPosition
from kalshi.model.ranged_market_position import RangedMarketPosition


class TestRangedMarketPosition(unittest.TestCase):
    """RangedMarketPosition unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRangedMarketPosition(self):
        """Test RangedMarketPosition"""
        # FIXME: construct object with mandatory attributes with example values
        # model = RangedMarketPosition()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
