"""
    Kalshi API.

    This documentation describes Kalshi's REST API  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import kalshi
from kalshi.model.json_error import JSONError
from kalshi.model.order import Order
globals()['JSONError'] = JSONError
globals()['Order'] = Order
from kalshi.model.user_batch_orders_cancel_single_order_response import UserBatchOrdersCancelSingleOrderResponse


class TestUserBatchOrdersCancelSingleOrderResponse(unittest.TestCase):
    """UserBatchOrdersCancelSingleOrderResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUserBatchOrdersCancelSingleOrderResponse(self):
        """Test UserBatchOrdersCancelSingleOrderResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = UserBatchOrdersCancelSingleOrderResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
