"""
    Kalshi API.

    This documentation describes Kalshi's REST API  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import kalshi
from kalshi.api.series_api import SeriesApi  # noqa: E501


class TestSeriesApi(unittest.TestCase):
    """SeriesApi unit test stubs"""

    def setUp(self):
        self.api = SeriesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_series_by_ticker(self):
        """Test case for get_series_by_ticker

        GetSeriesByTicker  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
