"""
    Kalshi API.

    This documentation describes Kalshi's REST API  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import kalshi
from kalshi.model.json_error import JSONError


class TestJSONError(unittest.TestCase):
    """JSONError unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testJSONError(self):
        """Test JSONError"""
        # FIXME: construct object with mandatory attributes with example values
        # model = JSONError()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
