"""
    Kalshi API.

    This documentation describes Kalshi's REST API  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import kalshi
from kalshi.model.user_order_create_request import UserOrderCreateRequest
globals()['UserOrderCreateRequest'] = UserOrderCreateRequest
from kalshi.model.user_batch_orders_create_request import UserBatchOrdersCreateRequest


class TestUserBatchOrdersCreateRequest(unittest.TestCase):
    """UserBatchOrdersCreateRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUserBatchOrdersCreateRequest(self):
        """Test UserBatchOrdersCreateRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = UserBatchOrdersCreateRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
